### ISSUE TITLE
Improve Flexslider Enqueue

### ISSUE THREAD

**Issue by raphaelkross** [sixteenbit/device-mockups#16]
Hi guys!

I notice that the scripts of Device Mockups are being globally linked even when dm-gallery shortcode is not being used. That brings a couple problems like CSS conflict and two extra requests to things that probably are not being even utilized.

So, I would suggest two things:

- Drop the dm_scripts function
- Add the wp_enqueue_style and wp_enqueue_script inside the dm_gallery_func (at first lines) and ensure the scripts are being enqueued at footer, not head, like it currently is...

This simple lines changes would improve performance and optimize the resources use of the plugin, so I hope you guys can change it and push to the official repo :)

Kind Regards,
Rafael

**Comment by mrdink** [comment]
Hey @raphaelkross,

Thanks for the help. We're right in the middle of refactoring the entire plugin. I do like the idea of enqueuing the script only when the dm-gallery is used but we'll need to enqueue the style globally due to it being needed to show the mocks.

Keep an eye out for 2.0.

**Comment by raphaelkross** [comment]
The main problem is not with the main style, but with the Flexslider CSS that is not necessary at all to be displayed if we are not using the Gallery feature :)

Maybe you could release just this change as a hotfix before doing the whole refactor, since this way would be faster. I could even help with that!

Kind Regards!

**Comment by mrdink** [comment]
Hey @raphaelkross,

Just pushed a pretty big update to the WordPress repository. It includes an improved way of enqueuing styles and scripts only when the shortcodes are used.

Thank you for bringing this to my attention. Test out the new version and let me know if there are any bugs. :smile: 

JP
