### ISSUE TITLE
Support shortcode use in page builders like OptimizePress

### ISSUE THREAD

**Issue by bghouse** [sixteenbit/device-mockups#21]
Hello, 
I'm trying to use your plugin when building landing pages with OptimizePress and it wont display.  Can support for this be added?

**Comment by justin-peacock** [comment]
Can you paste what shortcode you're using or a link to where it's not working?

**Comment by bghouse** [comment]
Hi, 
I ended up switching to Visual Composer and doing a custom mapping for the shortcode in VC to get this working.  Sorry but site is not live and cannot link per client until live.  I gave up on OptimizePress for multiple reasons :-)

**Comment by justin-peacock** [comment]
Gotcha

It definitely seemed like it was more of a conflict with that plugin rather than an issue with Device Mockups itself.

Glad you got it working!
